#!/bin/bash

#############################
# Specifications
#############################

# Project name
PROJECT_NAME=bigcode

#Docker names
DOCKER_IMAGE_NAME="$PROJECT_NAME-builder"
DOCKER_CONTAINER_NAME="$PROJECT_NAME-builder"
DOCKER_FILE_NAME="builder.Dockerfile"
#############################
# Input Parameters
#############################

TASK=$1

#############################
# Environment
#############################

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_HOST_DIR="$SCRIPT_DIR/../"
PROJECT_CONTAINER_DIR="/home/builder/workspace"

#############################
# Logic
#############################

#Print helpe if requested
if [ "$TASK" = "help" ]
then
	echo "Commands:"
	echo "	1. Initialize container: builder init"
	echo "	2. Run container: builder"
	echo "	3. Remove container: builder clear"
	exit 0
fi

case $TASK in
init)
	sudo docker build $SCRIPT_DIR -f "$SCRIPT_DIR/$DOCKER_FILE_NAME"  --tag=$DOCKER_IMAGE_NAME
	sudo docker run -v "$PROJECT_HOST_DIR:$PROJECT_CONTAINER_DIR" --name $DOCKER_CONTAINER_NAME --hostname "$DOCKER_CONTAINER_NAME" -it $DOCKER_IMAGE_NAME 
	;;
clear)
	sudo docker container rm $DOCKER_CONTAINER_NAME 
	sudo docker image rm $DOCKER_CONTAINER_NAME 
	;;
build)
	sudo docker start $DOCKER_CONTAINER_NAME
	sudo docker exec -ti $DOCKER_CONTAINER_NAME ./gradlew build
	sudo docker stop $DOCKER_CONTAINER_NAME
	;; 
*)	
	sudo docker start -i $DOCKER_CONTAINER_NAME
	;;
esac

